title: Technical Information
description: A starter template for a Jeykll site using the Just the Docs theme!
theme: just-the-docs

url: https://sergio-rojas-aragon.github.io/technical-documentation/


# color_scheme: dark
color_scheme: custom

# Enable or disable the site search
# Supports true (default) or false
search_enabled: true

search:
  # Split pages into sections that can be searched individually
  # Supports 1 - 6, default: 2
  heading_level: 2
  # Maximum amount of previews per search result
  # Default: 3
  previews: 3
  # Maximum amount of words to display before a matched word in the preview
  # Default: 5
  preview_words_before: 5
  # Maximum amount of words to display after a matched word in the preview
  # Default: 10
  preview_words_after: 10
  # Set the search token separator
  # Default: /[\s\-/]+/
  # Example: enable support for hyphenated search words
  tokenizer_separator: /[\s/]+/
  # Display the relative url in search results
  # Supports true (default) or false
  rel_url: true
  # Enable or disable the search button that appears in the bottom right corner of every page
  # Supports true or false (default)
  button: false
  # Focus the search input by pressing `ctrl + focus_shortcut_key` (or `cmd + focus_shortcut_key` on macOS)
  focus_shortcut_key: 'k'

# Enable or disable the side/mobile menu globally
# Nav menu can also be selectively enabled or disabled using page variables or the minimal layout
nav_enabled: true

# Supports true (default) or false
heading_anchors: true

aux_links:
  "Repo on Github":
    - "https://github.com/sergio-rojas-aragon/technical-documentation"

mermaid:
  # Version of mermaid library
  # Pick an available version from https://cdn.jsdelivr.net/npm/mermaid/
  version: "9.1.3"



# callouts_level: quiet # or loud
# callouts:
#   highlight:
#     color: yellow
#   important:
#     title: Important
#     color: blue
#   new:
#     title: New
#     color: green
#   note:
#     title: Note
#     color: purple
#   warning:
#     title: Warning
#     color: red